name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        run: |
          sudo apt-get install -y lftp
          lftp -c "set sftp:auto-confirm yes; open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} sftp://${{ secrets.FTP_HOST }}; mirror -R --verbose . /pllv4/"
